import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./GlobalRedux/provider";

export const metadata: Metadata = {
  title: "Control Plane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
